config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => "admin#index"
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  
  resources :products do
    get :who_bought, :on => :member
  end
  
  get "store/index"

  resources :products
  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
		<%= render @cart %>
      <% end %>
      <%end%>
      
      <% if session[:user_id] %>
        
        <%= link_to 'Home', store_path %><br />
        <%= link_to 'Orders', orders_path %><br />
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users', users_path %><br />
        <br />
        <%= button_to 'Logout', logout_path, :method => :delete %>
        
      <% else %>
      
        <%= link_to 'Home', store_path %><br />
      
      <% end %>
      
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>